name: Backend tests

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd backend || exit
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt; 
          else
            echo "No requirements.txt found. Stoping tests."
            return 1
          fi
      - name: Test with pytest
        run: |
          pytest